In [8]:
import pandas as pd
import numpy as np

In [9]:
data=pd.read_csv(r"C:\Users\DELL\Downloads\fsdsmendtoend-main\fsdsmendtoend-main\notebooks\data\gemstone.csv.csv")

In [10]:
data.drop(labels=["Unnamed: 0"],axis=1,inplace=True)

In [11]:
data

       carat        cut color clarity  depth  table     x     y     z  price
0       0.30      Ideal     E     SI1   62.1   58.0  4.27  4.29  2.66    499
1       0.33    Premium     G      IF   60.8   58.0  4.42  4.46  2.70    984
2       0.90  Very Good     E    VVS2   62.2   60.0  6.04  6.12  3.78   6289
3       0.42      Ideal     F     VS1   61.6   56.0  4.82  4.80  2.96   1082
4       0.31      Ideal     F    VVS1   60.4   59.0  4.35  4.43  2.65    779
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
26962   1.11    Premium     G     SI1   62.3   58.0  6.61  6.52  4.09   5408
26963   0.33      Ideal     H      IF   61.9   55.0  4.44  4.42  2.74   1114
26964   0.51    Premium     E     VS2   61.7   58.0  5.12  5.15  3.17   1656
26965   0.27  Very Good     F    VVS2   61.8   56.0  4.19  4.20  2.60    682
26966   1.25    Premium     J     SI1   62.0   58.0  6.90  6.88  4.27   5166

[26967 rows x 10 columns]

In [12]:
X=data.drop(labels=["price"],axis=1)

In [13]:
y=data[["price"]]

In [14]:
X

       carat        cut color clarity  depth  table     x     y     z
0       0.30      Ideal     E     SI1   62.1   58.0  4.27  4.29  2.66
1       0.33    Premium     G      IF   60.8   58.0  4.42  4.46  2.70
2       0.90  Very Good     E    VVS2   62.2   60.0  6.04  6.12  3.78
3       0.42      Ideal     F     VS1   61.6   56.0  4.82  4.80  2.96
4       0.31      Ideal     F    VVS1   60.4   59.0  4.35  4.43  2.65
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
26962   1.11    Premium     G     SI1   62.3   58.0  6.61  6.52  4.09
26963   0.33      Ideal     H      IF   61.9   55.0  4.44  4.42  2.74
26964   0.51    Premium     E     VS2   61.7   58.0  5.12  5.15  3.17
26965   0.27  Very Good     F    VVS2   61.8   56.0  4.19  4.20  2.60
26966   1.25    Premium     J     SI1   62.0   58.0  6.90  6.88  4.27

[26967 rows x 9 columns]

In [15]:
y

       price
0        499
1        984
2       6289
3       1082
4        779
...      ...
26962   5408
26963   1114
26964   1656
26965    682
26966   5166

[26967 rows x 1 columns]

In [16]:
categorical_cols=X.select_dtypes(include='object').columns

In [17]:
categorical_cols

Index(['cut', 'color', 'clarity'], dtype='object')

In [18]:
numerical_cols=X.select_dtypes(exclude='object').columns

In [19]:
numerical_cols

Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [20]:
X.select_dtypes(include='object')

             cut color clarity
0          Ideal     E     SI1
1        Premium     G      IF
2      Very Good     E    VVS2
3          Ideal     F     VS1
4          Ideal     F    VVS1
...          ...   ...     ...
26962    Premium     G     SI1
26963      Ideal     H      IF
26964    Premium     E     VS2
26965  Very Good     F    VVS2
26966    Premium     J     SI1

[26967 rows x 3 columns]

In [21]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [22]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [23]:
num_pipeline=Pipeline(
    
    
    steps=[
        
        ('imputer',SimpleImputer()),
        ('scaler', StandardScaler())
    ]
    
    
)

In [24]:
cat_pipeline=Pipeline(
    
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories])),
        ('scaler', StandardScaler())
    ]
    
)

In [25]:
preprocessor=ColumnTransformer(
    [
        
        ('num_pipeline',num_pipeline,numerical_cols),
        ('cat_pipeline',cat_pipeline,categorical_cols)
    ]
)

In [26]:
X

       carat        cut color clarity  depth  table     x     y     z
0       0.30      Ideal     E     SI1   62.1   58.0  4.27  4.29  2.66
1       0.33    Premium     G      IF   60.8   58.0  4.42  4.46  2.70
2       0.90  Very Good     E    VVS2   62.2   60.0  6.04  6.12  3.78
3       0.42      Ideal     F     VS1   61.6   56.0  4.82  4.80  2.96
4       0.31      Ideal     F    VVS1   60.4   59.0  4.35  4.43  2.65
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
26962   1.11    Premium     G     SI1   62.3   58.0  6.61  6.52  4.09
26963   0.33      Ideal     H      IF   61.9   55.0  4.44  4.42  2.74
26964   0.51    Premium     E     VS2   61.7   58.0  5.12  5.15  3.17
26965   0.27  Very Good     F    VVS2   61.8   56.0  4.19  4.20  2.60
26966   1.25    Premium     J     SI1   62.0   58.0  6.90  6.88  4.27

[26967 rows x 9 columns]

In [27]:

## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=30)

In [28]:
preprocessor.fit_transform(X_train)

array([[ 0.56167397,  0.31982286, -0.6510053 , ...,  0.98358286,
         0.22628311,  0.57614757],
       [-0.60408689, -0.39681436,  1.58987791, ..., -0.81206587,
        -0.94554678, -0.6397238 ],
       [-0.52081826, -0.25348692, -1.09918195, ...,  0.98358286,
         0.81219806, -1.24765949],
       ...,
       [ 1.87315495,  0.7498052 , -0.20282866, ..., -0.81206587,
         0.81219806,  0.57614757],
       [-1.04124722,  1.03646009, -0.20282866, ..., -1.70989024,
        -1.53146173, -1.24765949],
       [-0.54163542, -0.68346925, -0.20282866, ...,  0.98358286,
        -1.53146173, -0.6397238 ]])

In [29]:
preprocessor.transform(X_test)

array([[-8.33075636e-01,  1.76495416e-01,  1.58987791e+00, ...,
         8.57584942e-02, -9.45546784e-01, -6.39723804e-01],
       [ 2.91050915e-01, -9.70124145e-01,  6.93524626e-01, ...,
         8.57584942e-02, -9.45546784e-01, -1.24765949e+00],
       [ 6.24125449e-01, -3.96814364e-01, -2.02828660e-01, ...,
         8.57584942e-02,  1.98402795e+00, -3.17881183e-02],
       ...,
       [-1.04124722e+00,  8.21468919e-01, -2.02828660e-01, ...,
        -8.12065874e-01, -3.59631838e-01, -3.17881183e-02],
       [ 4.36771024e-01, -1.81823197e-01,  6.93524626e-01, ...,
         8.57584942e-02,  2.26283109e-01, -6.39723804e-01],
       [ 4.15953865e-01, -1.01840275e-14,  1.14170127e+00, ...,
         8.57584942e-02, -9.45546784e-01, -1.24765949e+00]])

In [30]:
preprocessor.get_feature_names_out()

array(['num_pipeline__carat', 'num_pipeline__depth',
       'num_pipeline__table', 'num_pipeline__x', 'num_pipeline__y',
       'num_pipeline__z', 'cat_pipeline__cut', 'cat_pipeline__color',
       'cat_pipeline__clarity'], dtype=object)

In [31]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [32]:
X_train

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,0.561674,0.319823,-0.651005,0.704838,0.692859,0.723432,0.983583,0.226283,0.576148
1,-0.604087,-0.396814,1.589878,-0.533052,-0.486169,-0.533329,-0.812066,-0.945547,-0.639724
2,-0.520818,-0.253487,-1.099182,-0.409263,-0.376688,-0.410385,0.983583,0.812198,-1.247659
3,-0.999613,0.248159,-1.099182,-1.178523,-1.134635,-1.107067,0.983583,0.812198,0.576148
4,0.228599,0.964796,-0.651005,0.413049,0.330729,0.477544,-0.812066,0.812198,-0.031788
...,...,...,...,...,...,...,...,...,...
18871,-0.187744,-2.045080,2.038055,0.103577,0.044393,-0.150837,0.085758,0.226283,-0.639724
18872,0.436771,0.319823,0.245348,0.607575,0.558113,0.614148,0.085758,0.226283,-0.639724
18873,1.873155,0.749805,-0.202829,1.535992,1.543444,1.611360,-0.812066,0.812198,0.576148
18874,-1.041247,1.036460,-0.202829,-1.346523,-1.260959,-1.189030,-1.709890,-1.531462,-1.247659
18875,-0.541635,-0.683469,-0.202829,-0.426947,-0.359845,-0.451366,0.983583,-1.531462,-0.639724

In [33]:
X_test

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.833076,1.764954e-01,1.589878,-0.904419,-0.898829,-0.861180,0.085758,-0.945547,-0.639724
1,0.291051,-9.701241e-01,0.693525,0.536838,0.532848,0.409242,0.085758,-0.945547,-1.247659
2,0.624125,-3.968144e-01,-0.202829,0.819784,0.734967,0.709771,0.085758,1.984028,-0.031788
3,0.832297,-1.328443e+00,2.934408,0.978942,0.886556,0.737092,-1.709890,-0.945547,-0.639724
4,-1.041247,-2.534869e-01,0.693525,-1.293470,-1.210430,-1.243672,-0.812066,0.226283,2.399955
...,...,...,...,...,...,...,...,...,...
8086,-0.166927,-1.471770e+00,0.693525,0.032840,0.069658,-0.109855,-0.812066,-0.945547,-1.247659
8087,-0.166927,-9.701241e-01,0.245348,0.032840,0.069658,-0.055213,-0.812066,0.226283,1.184083
8088,-1.041247,8.214689e-01,-0.202829,-1.293470,-1.218851,-1.161709,-0.812066,-0.359632,-0.031788
8089,0.436771,-1.818232e-01,0.693525,0.660627,0.583378,0.586827,0.085758,0.226283,-0.639724
8090,0.415954,-1.018403e-14,1.141701,0.607575,0.600221,0.545846,0.085758,-0.945547,-1.247659

In [34]:
"""linear regression
ridge regression
lasso regression
elastic net"""

'linear regression\nridge regression\nlasso regression\nelastic net'

In [35]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [36]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [37]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

In [38]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [39]:
list(models)

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [40]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(model)

LinearRegression()
Lasso()
Ridge()
ElasticNet()

In [41]:
models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet'])

In [42]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet()])

In [43]:


for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    #this is a validation(test) score
    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 1179.636139964177
MAE: 813.7992475074371
R2 score 91.4418612352779
===================================


Lasso
Model Training Performance
RMSE: 1180.826918395675
MAE: 815.4098852945368
R2 score 91.42457456481759
===================================


Ridge
Model Training Performance
RMSE: 1179.8147744717799
MAE: 814.0651177103246
R2 score 91.43926908909764
===================================


Elasticnet
Model Training Performance
RMSE: 1629.263755438059
MAE: 1079.232960563535
R2 score 83.67451929691354
===================================

In [44]:
trained_model_list

[]

In [45]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [46]:
r2_list

[0.914418612352779, 0.914245745648176, 0.9143926908909763, 0.8367451929691354]